const CONTENT_BUILDER_BUTTON_ACTION_TYPE_ANOTHER_SCREEN = 'another-screen';
const CONTENT_BUILDER_BUTTON_ACTION_TYPE_CLOSE = 'close';
const CONTENT_BUILDER_BUTTON_ACTION_TYPE_URL_OR_DEEP_LINK = 'url-or-deep-link';
const CONTENT_BUILDER_BUTTON_ACTION_TYPES = [
  CONTENT_BUILDER_BUTTON_ACTION_TYPE_ANOTHER_SCREEN,
  CONTENT_BUILDER_BUTTON_ACTION_TYPE_CLOSE,
  CONTENT_BUILDER_BUTTON_ACTION_TYPE_URL_OR_DEEP_LINK
];

const CONTENT_BUILDER_BUTTON_ACTION_TYPE_ANOTHER_SCREEN_VALUE = '';
const CONTENT_BUILDER_BUTTON_ACTION_TYPE_CLOSE_VALUE = '&cly_x_close=1';
const CONTENT_BUILDER_BUTTON_ACTION_TYPE_URL_OR_DEEP_LINK_VALUE = '';

const CONTENT_BUILDER_BUTTON_ACTION_VALUE_BY_ACTION_TYPE = {
  [CONTENT_BUILDER_BUTTON_ACTION_TYPE_ANOTHER_SCREEN]: CONTENT_BUILDER_BUTTON_ACTION_TYPE_ANOTHER_SCREEN_VALUE,
  [CONTENT_BUILDER_BUTTON_ACTION_TYPE_CLOSE]: CONTENT_BUILDER_BUTTON_ACTION_TYPE_CLOSE_VALUE,
  [CONTENT_BUILDER_BUTTON_ACTION_TYPE_URL_OR_DEEP_LINK]: CONTENT_BUILDER_BUTTON_ACTION_TYPE_URL_OR_DEEP_LINK_VALUE
}

const DEFAULT_CONTENT_BUILDER_BUTTON_ACTION = CONTENT_BUILDER_BUTTON_ACTION_TYPE_CLOSE;
const DEFAULT_CONTENT_BUILDER_BUTTON_BACKGROUND_COLOR = '#0166D6';
const DEFAULT_CONTENT_BUILDER_BUTTON_BORDER_RADIUS = 8;
const DEFAULT_CONTENT_BUILDER_BUTTON_COLOR = '#F6F6F6';
const DEFAULT_CONTENT_BUILDER_BUTTON_FONT_FAMILY = 'Inter';
const DEFAULT_CONTENT_BUILDER_BUTTON_HORIZONTAL_PADDING = 15;
const DEFAULT_CONTENT_BUILDER_BUTTON_HOVER_BACKGROUND_COLOR = '#F6F6F6';
const DEFAULT_CONTENT_BUILDER_BUTTON_HOVER_COLOR = '#0166D6';
const DEFAULT_CONTENT_BUILDER_BUTTON_TEXT = 'Click me';
const DEFAULT_CONTENT_BUILDER_BUTTON_VERTICAL_PADDING = 6;

export default {
  CONTENT_BUILDER_BUTTON_ACTION_TYPES,
  CONTENT_BUILDER_BUTTON_ACTION_VALUE_BY_ACTION_TYPE,
  DEFAULT_CONTENT_BUILDER_BUTTON_ACTION,
  DEFAULT_CONTENT_BUILDER_BUTTON_BACKGROUND_COLOR,
  DEFAULT_CONTENT_BUILDER_BUTTON_BORDER_RADIUS,
  DEFAULT_CONTENT_BUILDER_BUTTON_COLOR,
  DEFAULT_CONTENT_BUILDER_BUTTON_FONT_FAMILY,
  DEFAULT_CONTENT_BUILDER_BUTTON_HORIZONTAL_PADDING,
  DEFAULT_CONTENT_BUILDER_BUTTON_HOVER_BACKGROUND_COLOR,
  DEFAULT_CONTENT_BUILDER_BUTTON_HOVER_COLOR,
  DEFAULT_CONTENT_BUILDER_BUTTON_TEXT,
  DEFAULT_CONTENT_BUILDER_BUTTON_VERTICAL_PADDING
}

export {
  CONTENT_BUILDER_BUTTON_ACTION_TYPES,
  CONTENT_BUILDER_BUTTON_ACTION_VALUE_BY_ACTION_TYPE,
  DEFAULT_CONTENT_BUILDER_BUTTON_ACTION,
  DEFAULT_CONTENT_BUILDER_BUTTON_BACKGROUND_COLOR,
  DEFAULT_CONTENT_BUILDER_BUTTON_BORDER_RADIUS,
  DEFAULT_CONTENT_BUILDER_BUTTON_COLOR,
  DEFAULT_CONTENT_BUILDER_BUTTON_FONT_FAMILY,
  DEFAULT_CONTENT_BUILDER_BUTTON_HORIZONTAL_PADDING,
  DEFAULT_CONTENT_BUILDER_BUTTON_HOVER_BACKGROUND_COLOR,
  DEFAULT_CONTENT_BUILDER_BUTTON_HOVER_COLOR,
  DEFAULT_CONTENT_BUILDER_BUTTON_TEXT,
  DEFAULT_CONTENT_BUILDER_BUTTON_VERTICAL_PADDING
}
