const CONTENT_BUILDER_CARD_SHADOW_COLOR_DARK = 'dark';
const CONTENT_BUILDER_CARD_SHADOW_COLOR_LIGHT = 'light';

const CONTENT_BUILDER_CARD_SHADOW_COLORS = [
  CONTENT_BUILDER_CARD_SHADOW_COLOR_DARK,
  CONTENT_BUILDER_CARD_SHADOW_COLOR_LIGHT
]

const CONTENT_BUILDER_CARD_TYPE_FULLSCREEN = 'fullscreen';
const CONTENT_BUILDER_CARD_TYPE_HALF_MODAL = 'half-modal';
const CONTENT_BUILDER_CARD_TYPE_MODAL = 'modal';
const CONTENT_BUILDER_CARD_TYPE_STICKY = 'sticky';

const CONTENT_BUILDER_CARD_TYPES = [
  CONTENT_BUILDER_CARD_TYPE_FULLSCREEN,
  CONTENT_BUILDER_CARD_TYPE_HALF_MODAL,
  CONTENT_BUILDER_CARD_TYPE_MODAL,
  CONTENT_BUILDER_CARD_TYPE_STICKY
];

const DEFAULT_CONTENT_BUILDER_CARD_BACKGROUND_COLOR = '#FFFFFF';
const DEFAULT_CONTENT_BUILDER_CARD_BORDER_RADIUS = 16;
const DEFAULT_CONTENT_BUILDER_CARD_SHADOW = false;
const DEFAULT_CONTENT_BUILDER_CARD_SHADOW_COLOR = CONTENT_BUILDER_CARD_SHADOW_COLOR_DARK;
const DEFAULT_CONTENT_BUILDER_CARD_TYPE = CONTENT_BUILDER_CARD_TYPE_STICKY;

export default {
  DEFAULT_CONTENT_BUILDER_CARD_BACKGROUND_COLOR,
  DEFAULT_CONTENT_BUILDER_CARD_BORDER_RADIUS,
  DEFAULT_CONTENT_BUILDER_CARD_SHADOW,
  DEFAULT_CONTENT_BUILDER_CARD_SHADOW_COLOR,
  DEFAULT_CONTENT_BUILDER_CARD_TYPE,
  CONTENT_BUILDER_CARD_SHADOW_COLOR_DARK,
  CONTENT_BUILDER_CARD_SHADOW_COLOR_LIGHT,
  CONTENT_BUILDER_CARD_SHADOW_COLORS,
  CONTENT_BUILDER_CARD_TYPE_FULLSCREEN,
  CONTENT_BUILDER_CARD_TYPE_HALF_MODAL,
  CONTENT_BUILDER_CARD_TYPE_MODAL,
  CONTENT_BUILDER_CARD_TYPE_STICKY,
  CONTENT_BUILDER_CARD_TYPES
}

export {
  DEFAULT_CONTENT_BUILDER_CARD_BACKGROUND_COLOR,
  DEFAULT_CONTENT_BUILDER_CARD_BORDER_RADIUS,
  DEFAULT_CONTENT_BUILDER_CARD_SHADOW,
  DEFAULT_CONTENT_BUILDER_CARD_SHADOW_COLOR,
  DEFAULT_CONTENT_BUILDER_CARD_TYPE,
  CONTENT_BUILDER_CARD_SHADOW_COLOR_DARK,
  CONTENT_BUILDER_CARD_SHADOW_COLOR_LIGHT,
  CONTENT_BUILDER_CARD_SHADOW_COLORS,
  CONTENT_BUILDER_CARD_TYPE_FULLSCREEN,
  CONTENT_BUILDER_CARD_TYPE_HALF_MODAL,
  CONTENT_BUILDER_CARD_TYPE_MODAL,
  CONTENT_BUILDER_CARD_TYPE_STICKY,
  CONTENT_BUILDER_CARD_TYPES
}
