const CONTENT_BUILDER_IMAGE_RESOLUTION_FULL = 'full';
const CONTENT_BUILDER_IMAGE_RESOLUTION_LARGE = 'large';
const CONTENT_BUILDER_IMAGE_RESOLUTION_MEDIUM = 'medium';
const CONTENT_BUILDER_IMAGE_RESOLUTION_SMALL = 'small';
const CONTENT_BUILDER_IMAGE_RESOLUTIONS = [
  CONTENT_BUILDER_IMAGE_RESOLUTION_FULL,
  CONTENT_BUILDER_IMAGE_RESOLUTION_LARGE,
  CONTENT_BUILDER_IMAGE_RESOLUTION_MEDIUM,
  CONTENT_BUILDER_IMAGE_RESOLUTION_SMALL
];

const CONTENT_BUILDER_IMAGE_SIZE_FULL = 'full';
const CONTENT_BUILDER_IMAGE_SIZE_LARGE = 'large';
const CONTENT_BUILDER_IMAGE_SIZE_MEDIUM = 'medium';
const CONTENT_BUILDER_IMAGE_SIZE_SMALL = 'small';
const CONTENT_BUILDER_IMAGE_SIZES = [
  CONTENT_BUILDER_IMAGE_SIZE_FULL,
  CONTENT_BUILDER_IMAGE_SIZE_LARGE,
  CONTENT_BUILDER_IMAGE_SIZE_MEDIUM,
  CONTENT_BUILDER_IMAGE_SIZE_SMALL
];

const DEFAULT_CONTENT_BUILDER_IMAGE_POSITION = '';
const DEFAULT_CONTENT_BUILDER_IMAGE_REPEAT = '';
const DEFAULT_CONTENT_BUILDER_IMAGE_RESOLUTION = CONTENT_BUILDER_IMAGE_RESOLUTION_SMALL;
const DEFAULT_CONTENT_BUILDER_IMAGE_SIZE = CONTENT_BUILDER_IMAGE_SIZE_SMALL;
const DEFAULT_CONTENT_BUILDER_IMAGE_SPACING = 24;
const DEFAULT_CONTENT_BUILDER_IMAGE_SRC = '';

export default {
  CONTENT_BUILDER_IMAGE_RESOLUTIONS,
  CONTENT_BUILDER_IMAGE_SIZES,
  DEFAULT_CONTENT_BUILDER_IMAGE_POSITION,
  DEFAULT_CONTENT_BUILDER_IMAGE_REPEAT,
  DEFAULT_CONTENT_BUILDER_IMAGE_RESOLUTION,
  DEFAULT_CONTENT_BUILDER_IMAGE_SIZE,
  DEFAULT_CONTENT_BUILDER_IMAGE_SPACING,
  DEFAULT_CONTENT_BUILDER_IMAGE_SRC
}

export {
  CONTENT_BUILDER_IMAGE_RESOLUTIONS,
  CONTENT_BUILDER_IMAGE_SIZES,
  DEFAULT_CONTENT_BUILDER_IMAGE_POSITION,
  DEFAULT_CONTENT_BUILDER_IMAGE_REPEAT,
  DEFAULT_CONTENT_BUILDER_IMAGE_RESOLUTION,
  DEFAULT_CONTENT_BUILDER_IMAGE_SIZE,
  DEFAULT_CONTENT_BUILDER_IMAGE_SPACING,
  DEFAULT_CONTENT_BUILDER_IMAGE_SRC
}
