const HTML_REGEX = /<\/?[a-z][\s\S]*>/i;

const DEFAULT_CONTENT_BUILDER_TEXT_BOX_COLOR = 'black';
const DEFAULT_CONTENT_BUILDER_TEXT_BOX_FONT_FAMILY = 'Inter';
const DEFAULT_CONTENT_BUILDER_TEXT_BOX_FONT_SIZE = 14;
const DEFAULT_CONTENT_BUILDER_TEXT_BOX_FONT_WEIGHT = 400;
const DEFAULT_CONTENT_BUILDER_TEXT_BOX_TEXT = '';

export default {
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_COLOR,
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_FONT_FAMILY,
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_FONT_SIZE,
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_FONT_WEIGHT,
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_TEXT,
  HTML_REGEX
}

export {
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_COLOR,
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_FONT_FAMILY,
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_FONT_SIZE,
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_FONT_WEIGHT,
  DEFAULT_CONTENT_BUILDER_TEXT_BOX_TEXT,
  HTML_REGEX
}
